

<link rel ='stylesheet' href= '/views/css/db/db.css' type = "text/css">


<div  class= "db-sql">

<h1><b>&nbsp;&nbsp;数据库查询执行：</b></h1>
<br/><br/>
<span >&nbsp;&nbsp;&nbsp;&nbsp;模块：</span>
<input type=text class='module'>
<br/><br/>
<span >&nbsp;&nbsp;&nbsp;&nbsp;表名：</span>
<input type=text class='tables'>
<br/><br/>
<span >&nbsp;&nbsp;&nbsp;&nbsp;select语句：</span>
<br/>
&nbsp;&nbsp;&nbsp;&nbsp;<textarea rows="3" cols="50" class='select-text'></textarea>
<br/><br/>
<span >&nbsp;&nbsp;&nbsp;&nbsp;where语句：</span>
<br/><br/>
&nbsp;&nbsp;&nbsp;&nbsp;<textarea rows="3" cols="50" class='where-text' ></textarea>
<br/><br/>
&nbsp;&nbsp;&nbsp;&nbsp;<input type ="button" value= "查询" style="width: 100px;height:30px;" class= 'sql-commit' />
<div class='sql-result'>

</div>
</div>


<script type="text/javascript"  src=" /views/js/db/db.js" ></script> 