<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<title>rqf</title>
<link rel ='stylesheet' href= '/views/css/home/index.css' type = "text/css">
<body>
<?php include_once PAGE . DS.'header.phtml';?>
<?php include_once PAGE . DS.'search.phtml';?>
<?php include_once PAGE . DS.'left.phtml';?>
<div class = 'body-div'>
<div class ='left-favorite'>
</div>
<div class="home-right">
<span class = 'home-lanmu'>最新上架>></span>
<div class = "home-new">

</div>
<span class = 'home-lanmu'>掌柜推荐>></span>
<div class = "home-favorite" >
</div>
<span class = 'home-lanmu'>热门点击>></span>
<div class = "home-tuijian">
</div> 

</div>
</div>


<?php include_once PAGE . DS.'bottom.phtml';?>
</body>
</html>