<?php 
$session = \yaf\session::getInstance();
$user = $session->m_user;
?>
<link rel ='stylesheet' href= '/views/page/css/header.css' type = "text/css">
<link rel ='stylesheet' href= '/views/page/css/base.css' type = "text/css">
<div class ='header' >
<div class ='body-div'>
<?php if (empty($user)):?>
<div style='float: left' > <a class ="head-login" href="javascript:;">登录账号</a></div>
<?php else:?>
<div style='float: left' > 欢迎您！<?php echo $user['user_name']?><a href="/verify/public/logout" class ="logout">注销</a></div>
<?php endif;?>
<div style='float: right'>购物车   我的收藏   会员中心</div>
</div>
</div>

<script type="text/javascript"  src=" /views/js/jquery-2.1.1.js"></script>
<script type="text/javascript"  src=" /views/page/js/header.js"></script>
<script type="text/javascript"  src=" /views/page/js/dsdialog.js"></script>
