<?php 
$categoryMapper = \Item\CategoryModel::getInstance();
$result = $categoryMapper->cateLists();
?>
<link rel ='stylesheet' href= '/views/page/css/left.css' type = "text/css">
<div class = 'left'>
<div class="left-div">
<ul>
<li class= "menu" id = 'left-home'>首页</li>
<?php 
foreach ($result as $res){
	echo '<li class = menu id='.$res['cate_id'].'>'.$res['cate_name'];
	if(!empty($res['n_cate'])){
        echo '<ul class=next-menu>';
		foreach ($res['n_cate'] as $next){
			echo '<li id='.$next['cate_id'].'>'.$next['cate_name'].'</li>';
		}
		echo '</ul></li>';
	}
}
?>
</ul>
</div>
</div>
