
<link rel ='stylesheet' href= '/views/page/css/vip.css' type = "text/css">
<div class = 'vip-left-menu'>
<ul class = 'vip-left-menu-ul' >
<li><h3>&nbsp;菜单</h3></li>
<li class='left-alter-info' >
<b>
修改资料</b>
</li>

<li class='left-my-order' >
<b>
我的订单</b>
</li>
<li  class='left-my-rate'>
<b>
我的评价</b>
</li>
<li class='left-my-add'>
<b>
收货地址</b>
</li>
<li>
<b class='left-my-purse'>
钱包管理</b>
</li>
<li>
<b class='left-leave-mess'>
留言反馈</b>
</li>

</ul>
</div>
<script type="text/javascript"  src=" /views/page/js/vip.js"></script>