<link rel ='stylesheet' href= '/views/css/item/category.css' type = "text/css">

<div class ='cate-add-div'>

<div class='cate-adds-divs'><br/>
<form id= "cate-form">
一级类目：<input type = 'text' id='cate-first' name='cate_first'/><br/><br/>
<span class = 'add-second-input'>添加一个二级类目</span>&nbsp;&nbsp;<span class = 'del-second-input'>删除一个二级类目</span><br/>
<ul class='cate-second-ul'>
</ul>
<hr/>
</form>
<div class= 'cate-sumit'>保存</div>
</div>
</div>
<script type="text/javascript"  src=" /views/js/item/category.js"></script>