
<link rel ='stylesheet' href= '/views/css/messageboard/message.css' type = "text/css">
<link rel ='stylesheet' href= '/views/css/page.css' type = "text/css">

<div class= 'mess-list' width=100% >
<h1 style="cursor: hand;color:blue"><span class='my-mess-div'>我的留言</span>&nbsp;&nbsp;<span class='leave-mess-div'>发布留言</span></h1>
<div class='show-list' >

<ul>
<li></li>
<?php foreach ($messes as $mess): ?>
<li> <?php echo $mess['create_time']; ?> </li>
<li> <?php echo $mess['message_content']; ?>  </li>
<li style='text-align: right;color:blue;cursor:hand;' id=<?php echo $mess['message_id']; ?>>
<span class='to-reply' >查看回复</span>&nbsp;&nbsp;&nbsp;<span class='del-mess'>删除</span></li>


<?php endforeach;?>

</ul>
<div class="tcdPageCode"></div>
</div>

<!-- 发布留言 -->
<div class ='send-mess' style="display:none;">
<br/><br/><br/>
<textarea cols=80 rows=10  class= 'mess-content'></textarea><br/><br/>
<span class ='commit-send'>提交</span>
</div>
</div>


<script src="/views/js/messageboard/message.js"></script>
<script src="/views/js/jquery.page.js"></script>
<script>
    $(".tcdPageCode").createPage({
        pageCount:<?php echo $pageCount?>,
        current:<?php echo $pageNum?>,
        backFn:function(p){
    		$.get('/messageboard/message/list',{
    			page_num:p,
    			},
    		function(data){
    		     $('.vip-right').html(data);	
    		});
        }
    });
</script>