<?php 
$session = \yaf\session::getInstance();
$user = $session->m_admin;
?>
<link rel ='stylesheet' href= '/views/page/css/header.css' type = "text/css">
<link rel ='stylesheet' href= '/views/page/css/base.css' type = "text/css">
<div class ='header' >
<div style='float: right' > 欢迎您~ <?php echo $user['admin_name']?><a href="/index/logout" class ="logout"> &nbsp;退出  &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;</a></div>
</div>

<script type="text/javascript"  src=" /views/js/jquery-2.1.1.js"></script>
<script type="text/javascript"  src=" /views/page/js/left.js"></script>
<script type="text/javascript"  src=" /views/page/js/dsdialog.js"></script>
