

<link rel ='stylesheet' href= '/views/css/order/list.css' type = "text/css">
<link rel ='stylesheet' href= '/views/css/page.css' type = "text/css">


<div  class= "order-lists">

<div class= 'order-title'>
<b>订单管理</b>
</div>
<select  id = "order-status">
<option value=0 selected="selected">请选择状态</option>
<option value=-1 >未付款</option>
<option value=1 >待发货</option>
<option value=2 >待确认收货</option>
<option value=3 >待评价</option>
<option value=4 >已完成</option>
<option value=5 >已关闭</option>
</select>  

<div class='order-list-div'>

<table width=100%>
<tr>
<td width=30%>商品信息</td><td width=5%;>收货人</td><td width=20%>收货地址</td><td width=10%>联系号码</td><td width=10%>快递单号</td><td width=10%;>快递公司</td><td width=10% >订单状态</td><td width=5% >操作</td></tr>
<?php foreach ($orders as $order ): ?>
<tr>
<td class="item-td" width=30%;>
<img src = <?php echo $order['item_img'];?> class='item-img' />
<a href= "http://renqingfan.com/item/item/detail?item_id=<?php echo $order['item_id'];?>" >
<?php echo $order['item_title']?></a>
</td>

<td width=5%;>
<?php echo $order['receiver_name']; ?>
</td>

<td width=20%;>
<?php echo $order['receiver_address']; ?>
</td>

<td width=10%;>
<?php echo $order['receiver_mobile']; ?>
</td>

<td width=10%;>
<?php if($order['order_add_num'] == 0){
    	if ($order['order_status'] == 1){
            echo "<input type=text class=order-add-num$order[order_id] id= $order[order_id] value=输入快递单号>";
    	}
       }else{
       	echo $order['order_add_num'] ;
       } 
?>
</td>

<td width=10%;>
<?php 
if($order['order_add_num'] == 0){
    if ($order['order_status'] == 1){
        echo "<input type=text class=order-add$order[order_id] id= $order[order_id] value=输入快递公司> ";
    }
}else{
    echo $order['order_add_num'] ;
}

?>
</td>


<td width=10%;>
<?php 
switch ($order['order_status'])
{
	case 0:
	    echo '待付款';
	    break;
	case 1:
	    echo '待发货';
	    break;
	case 2:
	    echo '待确认收货';
	    break;
	case 3:
	    echo '待评价';
	    break;
	case 4:
	    echo '订单完成';
	    break;
    case 5:
        echo '订单关闭';
        break;
	default:
	    echo '删除';
}


?>
</td>
<td width=5%; id=<?php echo $order['order_id'];?>>
<?php 
switch ($order['order_status'])
{
	case 0:
	    echo '<span id=1 class=order-opera >关闭</span>';
	    break;
    case 1:
        echo '<span id=2 class=order-opera >发货</span>';
        break;
    case 2:
        break;
    case 3:
        break;
    case 4:
        echo '<span id=3 class=order-opera >删除</span>';
        break;
}

?>
</td>
</tr>
<?php endforeach;?>
<tr><td colspan = 8 class ='page-td'><div class="tcdPageCode"></div></td></tr>
</table>
</div>


</div>
<script type="text/javascript"  src=" /views/js/order/list.js"></script>
<script src="/views/js/jquery.page.js"></script>
<script>
    $(".tcdPageCode").createPage({
        pageCount:<?php echo $pageCount?>,
        current:<?php echo $pageNum?>,
        backFn:function(p){
        	var status =$("#order-status").val();
    		$.get('/vip/order/list',{
    			status : status,
    			page_num:p,
    			},
    		function(data){
    		     $('.right-div').html(data);	
    		});
        }
    });
</script>