<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<title>沐子家</title>

<link rel ='stylesheet' href= '/views/css/vip/order.css' type = "text/css">
<body>
<?php include_once PAGE . DS.'header.phtml';?>
<div class = 'body-div'>

<div class= 'pay-div'>
<div class='pay-title' ><b>订单付款：</b></div>

<div class='address-detail' ><b>收货信息：</b><br/><br/><br/>
<?php echo '收货地址：'.$order['receiver_address']."&nbsp;&nbsp;&nbsp;联系人：".$order['receiver_name'].'&nbsp;&nbsp;手机号：'.$order['receiver_mobile'];?>
</div>


<div class= 'pay-money'>
<h2><b>金额：</b></h2>
<span style="color:red;font-size:20px;" ><b><?php echo '￥'.$order['order_pay'] ?></b></span>
<br/>
<br/>
<div class= 'pay-order'><b>结算</b></div>
</div>


</div>
</div>
</body>
<script>
var orderId = <?php echo $order['order_id'];?>;
</script>
<script type="text/javascript"  src=" /views/js/vip/order.js"></script>
</html>