<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<title>沐子家</title>
<link rel ='stylesheet' href= '/views/css/shop/goodsdetail.css' type = "text/css">
<body>
<?php include_once PAGE . DS.'header.phtml';?>
<?php include_once PAGE . DS.'left.phtml';?>
<div class = 'body-div'>

<div class = 'goods-info'>
</div>


<div class = 'goods-right'>
</div>

<div class = 'goods-left'>

</div>







</div>

<!-- 宝贝描述 -->
<div class ='goods-description'>
</div>





</div>
</body>

</html>