<link rel ='stylesheet' href= '/views/css/item/list.css' type = "text/css">

<div class='cate-list' >

<div class ='list-left'>
</div>

<div class="list-right">
<ul >
<?php foreach ($items as $res): ?>
	<li class='item-list-li'>
	<img src=<?php echo $res['item_img']; ?> class ='right-main-image' />
<br/><br/>
<a href =<?php echo "/item/item/detail?item_id=$res[item_id]"; ?> >
<span class= 'itme-title'>
<?php echo mb_substr($res['item_title'],0,18,'utf-8').'>>>';?>
</span>
</a>
<br/><br/>
<span class='item-prices' >
<?php 
    if (!empty($res['item_promo_price'])){
	   echo '售价：<span style=text-decoration:line-through >'.$res['item_price'].
	   '</span>&nbsp;&nbsp;'.$res['item_price'].'&nbsp;元';
    }else {
	   echo '售价：'.$res['item_price'].'&nbsp;元';
    }
?>
</span>
	</li>
	<?php endforeach;?>
	
</ul>
</div>
</div>