<link rel ='stylesheet' href= '/views/css/item/item.css' type = "text/css">

<link href="/views/edit/themes/default/css/umeditor.css" type="text/css" rel="stylesheet">
    <script type="text/javascript" charset="utf-8" src="/views/edit/umeditor.config.js"></script>
    <script type="text/javascript" charset="utf-8" src="/views/edit/umeditor.min.js"></script>
    <script type="text/javascript" src="/views/edit/lang/zh-cn/zh-cn.js"></script>
    <script type="text/javascript" src="/views/js/ajaxfileupload.js"></script>
    <style type="text/css">
        h1{
            font-family: "微软雅黑";
            font-weight: normal;
        }
        .btn {
            display: inline-block;
            *display: inline;
            padding: 4px 12px;
            margin-bottom: 0;
            *margin-left: .3em;
            font-size: 14px;
            line-height: 20px;
            color: #333333;
            text-align: center;
            text-shadow: 0 1px 1px rgba(255, 255, 255, 0.75);
            vertical-align: middle;
            cursor: pointer;
            background-color: #f5f5f5;
            *background-color: #e6e6e6;
            background-image: -moz-linear-gradient(top, #ffffff, #e6e6e6);
            background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#ffffff), to(#e6e6e6));
            background-image: -webkit-linear-gradient(top, #ffffff, #e6e6e6);
            background-image: -o-linear-gradient(top, #ffffff, #e6e6e6);
            background-image: linear-gradient(to bottom, #ffffff, #e6e6e6);
            background-repeat: repeat-x;
            border: 1px solid #cccccc;
            *border: 0;
            border-color: #e6e6e6 #e6e6e6 #bfbfbf;
            border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
            border-bottom-color: #b3b3b3;
            -webkit-border-radius: 4px;
            -moz-border-radius: 4px;
            border-radius: 4px;
            filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffffff', endColorstr='#ffe6e6e6', GradientType=0);
            filter: progid:DXImageTransform.Microsoft.gradient(enabled=false);
            *zoom: 1;
            -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);
            -moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);
            box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);
        }

        .btn:hover,
        .btn:focus,
        .btn:active,
        .btn.active,
        .btn.disabled,
        .btn[disabled] {
            color: #333333;
            background-color: #e6e6e6;
            *background-color: #d9d9d9;
        }

        .btn:active,
        .btn.active {
            background-color: #cccccc \9;
        }

        .btn:first-child {
            *margin-left: 0;
        }

        .btn:hover,
        .btn:focus {
            color: #333333;
            text-decoration: none;
            background-position: 0 -15px;
            -webkit-transition: background-position 0.1s linear;
            -moz-transition: background-position 0.1s linear;
            -o-transition: background-position 0.1s linear;
            transition: background-position 0.1s linear;
        }

        .btn:focus {
            outline: thin dotted #333;
            outline: 5px auto -webkit-focus-ring-color;
            outline-offset: -2px;
        }

        .btn.active,
        .btn:active {
            background-image: none;
            outline: 0;
            -webkit-box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.15), 0 1px 2px rgba(0, 0, 0, 0.05);
            -moz-box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.15), 0 1px 2px rgba(0, 0, 0, 0.05);
            box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.15), 0 1px 2px rgba(0, 0, 0, 0.05);
        }

        .btn.disabled,
        .btn[disabled] {
            cursor: default;
            background-image: none;
            opacity: 0.65;
            filter: alpha(opacity=65);
            -webkit-box-shadow: none;
            -moz-box-shadow: none;
            box-shadow: none;
        }
    </style>
    
<div class ='item-add-div'>

<div class = "save-item-div">
<input type="button" value = "保存宝贝编辑" id ="save-item-button" />
</div>


<table class='item-add-table'>

<tr><td>
<select  id = "select-father">  
<option value="0" selected="selected">请选择一级类目</option>
<?php 

    foreach ($cates as $cate){
        echo "<option value={$cate['cate_id']} >";
    	echo $cate['cate_name']."</option>";
    }


?>
</select> 
</td>
<td>
<select  id = "select-next">  
<option value="0" selected="selected">请选择一级类目</option>
</select> 
</td>
</tr>


<tr>
<td class="input-title">宝贝标题：</td><td><input type ="text" class="item-title-input" id= "item_title" /><span class="input-asign">&nbsp; *最多支持30个汉字</span></td>
</tr> 

<tr>
<td class="input-title">宝贝价格：</td><td><input type ="text" class="litle-input" id="item_price" /><span class="input-asign">&nbsp; *保留两位小数点</span></td>
</tr> 

<tr>
<td class="input-title">宝贝促销价：</td><td><input type ="text" class="litle-input" id="item_promo_price" /><span class="input-asign">&nbsp; *不填为原件售卖</span></td>
</tr> 

<tr>
<td class="input-title">库存数量：</td><td><input type ="text" class="litle-input" id="item_total" /><span class="input-asign">&nbsp; *至少5个</span></td>
</tr> 

<tr>
<td class="input-title">宝贝快递费：</td><td><input type ="text" class="litle-input" id="item_post" /><span class="input-asign">&nbsp; *保留两位小数点（不填为免邮）</span></td>
</tr> 

<tr>
<td class="input-title">宝贝颜色：</td><td><input type ="text" class="item-title-input" id="item_color" /><span class="input-asign">&nbsp; *多个颜色请用请用"英文"逗号(,)隔开</span></td>
</tr> 

<tr>
<td class="input-title">宝贝型号：</td><td><input type ="text" class="item-title-input" id="item_marque" /><span class="input-asign">&nbsp; *多个尺码请用请用"英文"逗号(,)隔开</span></td>
</tr>  

<tr>
<td class="input-title">宝贝主图：</td><td><input type="file" name ="upfileMain" id ="upfileMain" /> <span class="input-asign">&nbsp; <a href="javascript:;" id="upload-main" >上传主图</a></span></td>
</tr> 
<tr>
<td class="input-title"></td><td><img src="#" id= "main-img" /></td>
</tr> 
<tr>
<td class="input-title">缩略图：</td><td><input type="file" name ="upfileNext" id="upfileNext" /><span class="input-asign">&nbsp; <a href="javascript:;"  id="upload-next" >上传缩略图</a></span><span class="input-asign">&nbsp; *单击图片可删除该张缩略图</span></td>
</tr> 

<tr>
<td class="input-title"></td><td><div class="img-next-div" ><ul class="next-img-ul"></ul></div></td>
</tr> 
<tr>

</table>
<input type="hidden" id="images_next" value='' />

<div class='edit-text-edit' >
<textarea id="myEditor" style="width:800px;height:500px;" ></textarea>
</div>




</div>

<script type="text/javascript"  src=" /views/js/item/item.js"></script>
<script type="text/plain" id="myEditor" style="width:1000px;height:240px;">
    <p>这里我可以写一些输入提示</p>
</script>

<script type="text/javascript">
    //实例化编辑器
    var um = UM.getEditor('myEditor');
    um.addListener('blur',function(){
        $('#focush2').html('编辑器失去焦点了')
    });
    um.addListener('focus',function(){
        $('#focush2').html('')
    });
</script>