<link rel ='stylesheet' href= '/views/css/item/item.css' type = "text/css">

    <link href="../themes/default/_css/umeditor.css" type="text/css" rel="stylesheet">
    <script type="text/javascript" charset="utf-8" src="/views/edit/umeditor.config.js"></script>
    <script type="text/javascript" charset="utf-8" src="/views/edit/editor_api.js"></script>
    <script type="text/javascript" src="views/edit/lang/zh-cn/zh-cn.js"></script>
    
<div class ='item-add-div'>
<table border=1 class='item-add-table'>
<tr>
<td class="input-title">宝贝标题：</td><td><input type ="text" width="400px;"/></td>
</tr> 

<tr>
<td class="input-title">宝贝价格：</td><td><input type ="text" /></td>
</tr> 

<tr>
<td class="input-title">宝贝促销价：</td><td><input type ="text" /></td>
</tr> 

<tr>
<td class="input-title">库存数量：</td><td><input type ="text" /></td>
</tr> 

<tr>
<td class="input-title">宝贝快递费：</td><td><input type ="text" /></td>
</tr> 

<tr>
<td class="input-title">宝贝颜色：</td><td><input type ="text" /></td>
</tr> 

<tr>
<td class="input-title">宝贝型号：</td><td><input type ="text" /></td>
</tr> 
    <tr>
        <td>中国</td><td><textarea id="myEditor" style="width:800px;height:240px;"></textarea></td>
    </tr>

</table>



</div>
<script type="text/javascript"  src=" /views/js/item/item.js"></script>
<script type="text/javascript">
    var um = UM.getEditor('myEditor');
</script>