<link rel ='stylesheet' href= '/views/css/item/item.css' type = "text/css">

<div class ='item-add-div'>
<table border=1 class='item-add-table'>
<tr>
<td class="input-title">宝贝标题：</td><td><input type ="text" width="400px;"/></td>
</tr> 

<tr>
<td class="input-title">宝贝价格：</td><td><input type ="text" /></td>
</tr> 

<tr>
<td class="input-title">宝贝促销价：</td><td><input type ="text" /></td>
</tr> 

<tr>
<td class="input-title">库存数量：</td><td><input type ="text" /></td>
</tr> 

<tr>
<td class="input-title">宝贝快递费：</td><td><input type ="text" /></td>
</tr> 

<tr>
<td class="input-title">宝贝颜色：</td><td><input type ="text" /></td>
</tr> 

<tr>
<td class="input-title">宝贝型号：</td><td><input type ="text" /></td>
</tr> 

<tr>
<td></td><td></td>
</tr> 

<tr>
<td></td><td></td>
</tr> 

<tr>
<td></td><td></td>
</tr> 
</table>



</div>
<script type="text/javascript"  src=" /views/js/item/item.js"></script>